server:
  port: 9999
#  servlet:
#    context-path: /sp01
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署，false即不开启热部署
      additional-paths: src/main/java #指定热部署的目录
      #      exclude: test/**  #指定目录不更新
      ##http://localhost:9999/images/test.jpg   static-path-pattern静态资源路径映射
      #  mvc:
      #    static-path-pattern: images/**
      # 默认http://localhost:9999/test.jpg
  web:
    resources:
      static-locations: /upload/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:oracle:thin:@10.118.4.4:1525:hydeekf
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: h2
    password: hydeesoft