server:
  port: 9999
#  servlet:
#    context-path: /sp01
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署，false即不开启热部署
      additional-paths: src/main/java #指定热部署的目录
#      exclude: test/**  #指定目录不更新